"""empty message

Revision ID: 452cfdf7eb7f
Revises: 50d6286a4895
Create Date: 2024-11-19 11:13:40.238162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452cfdf7eb7f'
down_revision = '50d6286a4895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DATETIME(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
